export type TPlayer = {
    [index: string]: PropertyKey,
    id: number,
    firstName: string,
    lastName: string,
    fullName: string,
    currentTeamId: number,
    birthDate: string,
    birthCity: string,
    birthCountry: string,
    birthStateProvince: string,
    height: number,
    weight: number,
    currentAge: number,
    isActive: number,
    isAlternateCaptain: number,
    isCaptain: number,
    isRookie: number,
    link: string,
    nationality: string,
    primaryNumber: number,
    primaryPosition: string,
    rosterStatus: string,
    shootsCatches: string,
}

export type TTeam = {
    abbreviation: string,
    active: boolean,
    conferenceId: number,
    conferenceName: string,
    divisionId: number,
    divisionName: string,
    firstYearOfPlay: number,
    franchiseId: number,
    id: number,
    link: string,
    locationName: string,
    name: string,
    officialSiteUrl: string,
    players: TPlayer[],
    shortName: string,
    teamName: string,
    venueId: number,
    venueName: string,
}
