export type TTeam = {
    abbreviation: string,
    active: boolean,
    conferenceId: number,
    conferenceName: string,
    divisionId: number,
    divisionName: number,
    firstYearOfPlay: number,
    franchiseId: number,
    id: number,
    link: string,
    locationName: string,
    name: string,
    officialSiteUrl: string,
    shortName: string,
    teamName: string,
    venueId: number,
    venueName: string,
}
