export type TStanding = {
    [index: string]: PropertyKey,
    conferenceId: number,
    conferenceName: string,
    conferenceRank: number,
    conferenceL10Rank: number,
    conferenceHomeRank: number,
    conferenceRoadRank: number,
    divisionId: number,
    divisionName: string,
    divisionHomeRank: number,
    divisionL10Rank: number,
    divisionRank: number,
    divisionRoadRank: number,
    gamesPlayed: number,
    goalsAgainst: number,
    goalsFor: number,
    lastUpdated: string,
    leagueId: number,
    leagueRank: number,
    leagueL10Rank: number,
    leagueHomeRank: number,
    leagueRoadRank: number,
    points: number,
    pointsPercentage: number,
    ppConferenceRank: number,
    ppDivisionRank: number,
    ppLeagueRank: number,
    regulationWins: number,
    row: number,
    streak: string,
    teamId: number,
    teamName: string,
    wildCardRank: number,
}
